version: 2
updates:
  - package-ecosystem: npm
    directory: /wasm
    schedule:
      interval: weekly
    groups:
      stylelint:
        patterns:
          - stylelint*
      coffeescript:
        patterns:
          - '@coffeelint/*'
          - coffeescript
    labels:
      - 'domain:dependencies'
    versioning-strategy: increase-if-necessary
  - package-ecosystem: gitsubmodule
    directory: /tests/unit
    schedule:
      interval: monthly
    labels:
      - 'domain:dependencies'
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      artifacts:
        patterns:
          - actions/*-artifact
    labels:
      - 'domain:dependencies'
      - 'domain:CI/CD'
