version: 2
updates:
  - package-ecosystem: npm
    directory: /wasm
    schedule:
      interval: monthly
    labels:
      - 'domain:dependencies'
    versioning-strategy: increase-if-necessary
    groups:
      typescript-eslint:
        patterns:
          - '@typescript-eslint/*'
      eslint:
        patterns:
          - eslint
          - '@eslint/js'
      civet:
        patterns:
          - '@danielx/civet'
          - eslint-plugin-civet
  - package-ecosystem: gitsubmodule
    directory: /
    schedule:
      interval: monthly
    labels:
      - 'domain:dependencies'
      - 'domain:tests'
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    groups:
      artifacts:
        patterns:
          - actions/*-artifact
          - actions/deploy-pages
    labels:
      - 'domain:dependencies'
      - 'domain:CI/CD'
