version: 2
updates:
  - package-ecosystem: npm
    directory: /wasm
    schedule:
      interval: weekly
    labels:
      - 'domain:dependencies'
    versioning-strategy: increase-if-necessary
  - package-ecosystem: gitsubmodule
    directory: /
    schedule:
      interval: monthly
    labels:
      - 'domain:dependencies'
      - 'domain:tests'
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      artifacts:
        patterns:
          - actions/*-artifact
    labels:
      - 'domain:dependencies'
      - 'domain:CI/CD'
