name: a
'on':
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ^16.13.0
      - uses: numworks/setup-emscripten@latest # there is no v1 tag/branch
      - run: |
          set -e
          cd wasm
          npm ci --omit dev --no-fund
          ./build_wasm.sh
          npm run deploy
