#pragma once

#include <cstdint>

enum opcodes : int32_t {
    NOP = '.',
    ADD = '+',
    SUB = '-',
    MUL = '*',
    DIV = ':',
    MOD = '%',
    BNG_NW = '^',
    BNG_NE = '7',
    BNG_E = '>',
    BNG_SE = 'v',
    BNG_SW = 'L',
    BNG_W = '<',
    MIR_EW = '_',
    MIR_NS = '|',
    MIR_NESW = '/',
    MIR_NWSE = '\\',
    PSI = '\'',
    PSC = '"',
    POP = ',',
    EXT = '@',
    INC = ')',
    DEC = '(',
    AND = '&',
    IOR = 'r',
    XOR = 'x',
    NOT = '~',
    GTC = 'i',
    PTC = 'o',
    GTI = '?',
    PTI = '!',
    SKP = '#',
    LEA = 'j',
    DUP = '2',
    RND = '$',
};
