env:
  browser: true
  es2022: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/stylistic
  - plugin:@typescript-eslint/strict
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2022
plugins:
  - '@typescript-eslint'
rules:
  '@typescript-eslint/ban-ts-comment':
    - error
    - ts-nocheck: false
  '@typescript-eslint/consistent-type-imports': error
  '@typescript-eslint/default-param-last': error
  '@typescript-eslint/no-non-null-assertion': 'off'
  '@typescript-eslint/no-unused-vars': 'off'
  no-constant-condition:
    - error
    - checkLoops: false
  no-extra-semi: 'off'
  # https://github.com/eslint/eslint/issues/15896
  no-var: 'off'
  no-restricted-syntax:
    - error
    - selector: VariableDeclaration[kind='var'][declare!=true]
      message: Unexpected var, use let or const instead.
