name: Build & Release Precompiled Binaries
'on':
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
jobs:
  build-unix:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    name: Build for ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Compile C++ sources
        shell: bash
        run: >
          mkdir Release/

          tag=${{ github.ref_name }}

          g++ -O3 -DNDEBUG -DVERSION=$tag -flto -fno-rtti -std=gnu++17 -o Release/trilangle-${tag}-${{ matrix.os }}
          src/*.cpp
      - uses: actions/upload-artifact@v3
        with:
          name: trilangle-${{ matrix.os }}
          path: Release/
  build-windows:
    name: Build for Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ilammy/msvc-dev-cmd@v1.12.1
      - name: Compile C++ sources
        shell: cmd
        run: >
          MD Release

          SET tag=${{ github.ref_name }}

          CL .\src\*.cpp /O2 /EHsc /GL /GR- /DNDEBUG /DVERSION=%tag% /std:c++20 /MT /link
          /out:Release\trilangle-%tag%-windows-latest.exe
      - uses: actions/upload-artifact@v3
        with:
          name: trilangle-windows-latest
          path: Release/
  release:
    name: Release
    runs-on: ubuntu-latest
    needs:
      - build-unix
      - build-windows
    steps:
      - uses: actions/checkout@v3
      - run: "mkdir artifacts/\n"
      - uses: actions/download-artifact@v3
        with:
          path: artifacts/
      - name: Flatten artifacts directory
        # https://unix.stackexchange.com/a/52836
        run: |
          find artifacts -type f -exec sh -c 'mv "$@" artifacts' _ {} +
          find artifacts -depth -exec rmdir {} + || true
      - name: Parse changelog
        shell: bash
        run: |
          tag=${{ github.ref_name }}
          sed -n "s/^## \[${tag//./\\.}\].*$//m
          t loop
          d
          :loop
          n
          /^## /q
          p
          b loop" CHANGELOG.md >$tag-CHANGELOG.md
      - uses: softprops/action-gh-release@v1
        with:
          body_path: ${{ github.ref_name }}-CHANGELOG.md
          files: artifacts/*
