name: Lint C++ Builds
'on':
  push:
    branches:
      - '**'
    paths:
      - src/**
      - .clang-format
      - .github/workflows/lint-cpp-builds.yml
  workflow_dispatch: ~
jobs:
  build-native-mac:
    runs-on: macos-latest
    strategy:
      matrix:
        arch:
          - x86_64
          - aarch64
    name: Verify C++ Build with clang on ${{ matrix.arch }}
    steps:
      - uses: actions/checkout@v5
      - name: Invoke clang
        shell: bash
        run: >+
          clang++ -DVERSION=0.0.0 -DNDEBUG -WCL4 -Wnon-gcc -Wimplicit-fallthrough -Werror -std=c++17 -o /dev/null
          -target "$(clang -dumpmachine | sed -E 's/^\w+-/${{ matrix.arch }}-/')" src/*.cpp
  build-native-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        include:
          - cmd_arch: amd64
            disp_arch: x86_64
          - cmd_arch: amd64_x86
            disp_arch: x86
          - cmd_arch: amd64_arm64
            disp_arch: arm64
    name: Verify C++ Build with MSVC on ${{ matrix.disp_arch }}
    steps:
      - uses: actions/checkout@v5
      - uses: ilammy/msvc-dev-cmd@v1.13.0
        with:
          arch: ${{ matrix.cmd_arch }}
      - name: Invoke MSVC
        shell: pwsh
        # The standard library header <tuple> is giving warning C6031, but only in CI -- I can't reproduce it locally.
        # Since I can't seem to prevent it, just suppress the warning instead.
        run: |
          cl .\src\*.cpp /EHsc /DVERSION=0.0.0 /DNDEBUG /std:c++20 /MTd /analyze /W4 /WX /wd6031 /we5219
