name: Lint Builds
'on':
  push:
    branches:
      - '**'
    paths:
      # It would be nice if I could specify this per-job, but I'm not making a whole new file just to avoid running
      # clang for web-only changes.
      - src/*
      - wasm/*
      - .clang-format
      - .github/workflows/lint-build.yml
  pull_request:
    paths: !reference on.push.paths
  workflow_dispatch: ~
jobs:
  build-native:
    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}
    runs-on: macos-latest
    name: Verify C++ Build with clang
    steps:
      - uses: actions/checkout@v3
      - name: Invoke clang
        shell: bash
        run: >+
          clang++ -DVERSION=0.0.0 -DNDEBUG -WCL4 -Wnon-gcc -Wimplicit-fallthrough -Werror -std=c++14 -o /dev/null
          src/*.cpp
  lint-npm:
    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}
    runs-on: ubuntu-latest
    name: Lint with JS Tools
    steps:
      - uses: actions/checkout@v3
      - name: npm lint
        shell: bash
        run: |
          cd wasm
          npm ci --no-fund
          npm run lint
  verify-wasm-build:
    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}
    runs-on: ubuntu-latest
    name: Verify wasm build
    steps:
      # Largely copied from build-and-deploy-pages.jobs.build-wasm.steps
      - uses: actions/checkout@v3
      - uses: numworks/setup-emscripten@bbc4f5e15974bc13e69fdadecfd1858ecb1c4dbb
      - uses: actions/cache@v3
        with:
          path: /opt/hostedtoolcache/emscripten/latest/x64/upstream/emscripten/cache/sysroot/lib/wasm32-emscripten/lto
          key: libs-${{ hashFiles('~/work/Trilangle/Trilangle/emsdk/upstream/emscripten/system/lib/**.c') }}
          restore-keys: "libs-\n"
      - name: Run build script
        shell: bash
        run: |
          cd wasm
          npm ci --omit dev --no-fund
          ./build_wasm.sh
        # Some errors, especially with the closure compiler, don't surface in debug builds.
