name: Lint C++ Builds
'on':
  push:
    branches:
      - '**'
    paths:
      - src/**
      - .clang-format
      - .github/workflows/lint-cpp-builds.yml
  workflow_dispatch: ~
jobs:
  build-native-mac:
    runs-on: macos-latest
    strategy:
      matrix:
        arch:
          - x86_64
          - aarch64
    name: Verify C++ Build with clang on ${{ matrix.arch }}
    steps:
      - uses: actions/checkout@v4
      - name: Invoke clang
        shell: bash
        run: >+
          clang++ -DVERSION=0.0.0 -DNDEBUG -WCL4 -Wnon-gcc -Wimplicit-fallthrough -Werror -std=c++14 -o /dev/null
          -target "$(clang -dumpmachine | sed -E 's/^\w+-/${{ matrix.arch }}-/')" src/*.cpp
  build-native-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        include:
          - cmd_arch: amd64
            disp_arch: x86_64
          - cmd_arch: amd64_x86
            disp_arch: x86
          - cmd_arch: amd64_arm64
            disp_arch: arm64
    name: Verify C++ Build with MSVC on ${{ matrix.disp_arch }}
    steps:
      - uses: actions/checkout@v4
      - uses: ilammy/msvc-dev-cmd@v1.13.0
        with:
          arch: ${{ matrix.cmd_arch }}
      - name: Invoke MSVC
        shell: pwsh
        # Set warning 6031 to level 4 and check external headers at level 3, otherwise the STL header <tuple> emits
        # warning C6031. Set warning 5219 (implicit conversion, possible loss of data) as an error.
        run: >+
          cl .\src\*.cpp /EHsc /DVERSION=0.0.0 /DNDEBUG /std:c++20 /MTd /analyze /external:anglebrackets /external:W3
          /W4 /w46031 /we5219 /WX
