name: Run Tests
'on':
  push:
    branches:
      - '**'
    paths:
      - src/**
      - tests/**
      - .github/workflows/test.yml
      - .gitmodules
      - qdeql/interpreter.trg
  workflow_dispatch: ~
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    name: Run Unit Tests
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Compile and run unit tests
        shell: bash
        run: |
          shopt -s globstar extglob
          g++ -Og -Isrc tests/unit/**/*.cpp src/!(main).cpp
          ./a.out
  cli-tests-unix:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    name: Run CLI Tests for ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Build and run tests
        shell: bash
        run: "./clitest.sh\n"
  cli-tests-windows:
    runs-on: windows-latest
    name: Run CLI Tests for Windows
    steps:
      - uses: actions/checkout@v4
      - uses: ilammy/msvc-dev-cmd@v1.13.0
      - name: Compile C++ sources
        shell: pwsh
        run: |
          cl .\src\*.cpp /Od /EHs /std:c++20 /MTd /DNO_BUFFER /link /out:trilangle
      - name: Run test scripts
        # Screw it, I'm not figuring out how to make this work in PowerShell.
        shell: bash
        run: |
          for script in tests/cli/*/index.sh
          do
            echo "Running ${script}..."
            TRILANGLE=./trilangle "$script"
          done
