name: Run Tests
'on':
  push:
    branches:
      - '**'
    paths:
      - src/*
      - tests/**
      - .github/workflows/test.yml
      - .gitmodules
  pull_request:
    paths:
      - src/*
      - tests/**
      - .github/workflows/test.yml
      - .gitmodules
  workflow_dispatch: ~
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    name: Run Unit Tests
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Compile and run unit tests
        shell: bash
        run: |
          shopt -s globstar extglob
          g++ -Og -Isrc tests/unit/**/*.cpp src/!(main).cpp
          ./a.out
  cli-tests:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    name: Run CLI Tests for ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Build and run tests
        shell: bash
        run: |
          g++ -Og -std=gnu++17 src/*.cpp -o trilangle
          export PATH="${PATH}:${PWD}"
          for script in tests/cli/*/index.sh
          do
            echo "Running ${script}..."
            "$script"
          done
